# Generated by Django 5.2.4 on 2025-07-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills relevant to this position', null=True),
        ),
    ]
