# Generated by Django 5.2.4 on 2025-07-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0002_jobapplication_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for contact', max_length=20, null=True),
        ),
    ]
