# Generated by Django 5.2.4 on 2025-08-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('other', 'Other')], default='other', help_text='The industry the company operates in.', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001-5000', '1001-5000 employees'), ('5001+', '5001+ employees')], help_text='The size of the company in terms of number of employees.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.CharField(blank=True, help_text="The location of the company's headquarters.", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, help_text='The year the company was founded.', null=True),
        ),
    ]
