# Generated by Django 5.2.4 on 2025-08-16 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0005_alter_company_company_size_alter_company_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_recruiters', to='career_portal.company')),
                ('user', models.ForeignKey(db_column='user_id', limit_choices_to={'user_type': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_companies', to=settings.AUTH_USER_MODEL, verbose_name='recruiter')),
            ],
            options={
                'verbose_name': 'Recruiter Company Mapping',
                'verbose_name_plural': 'Recruiter Company Mappings',
                'db_table': 'recruiter_companies',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
