# Generated by Django 5.2.4 on 2025-08-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career_portal', '0007_create_recruiter_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitercompany',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recruiter_companies',
                limit_choices_to={'user_type': 'employer'},
                db_column='user_id',
                to='career_portal.user',
                verbose_name='recruiter'
            ),
        ),
    ]
